apiVersion: apps/v1
kind: Deployment
metadata:
  name: xopera-deployment
  namespace: xopera-namespace
  labels:
    app: xopera
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xopera
  template:
    metadata:
      labels:
        app: xopera
    spec:
      containers:
      - name: xopera
        image: sodaliteh2020/xopera-rest-api:2.7.0
        ports:
        - containerPort: 8080
        env:
        - name: DEBUG
          value: "true"
        - name: LOG_LEVEL
          value: debug
        envFrom:
          - secretRef:
              name: postgres-secrets
            prefix: XOPERA_DATABASE_
          - configMapRef:
              name: xopera-config
          - secretRef:
              name: xopera-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: xopera-service
  namespace: xopera-namespace
spec:
  selector:
    app: xopera
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xopera-ingress
  namespace: xopera-namespace
spec:
  tls:
  - hosts:
      - xopera.com
    secretName: xopera-secret-tls
  rules:
  - host: xopera.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xopera-service
            port:
              number: 8080